---
title: PlaDio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Blog for Pladio website
url: https://blog.pladio.co
baseurl: "/tale"
google_analytics: UA—XXXXXXXX-X
author:
  name: Pladio
  url: https://blog.pladio.co
  email: sales@pladio.co
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
permalink: "/:year-:month-:day/:title"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- tale.gemspec
