---
title: Tale
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Minimal Jekyll theme for storytellers
baseurl: "/tale"
url: https://chesterhow.github.io
google_analytics: UA—XXXXXXXX-X
author:
  name: Chester How
  url: https://chester.how
  email: chesterhow@gmail.com
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
permalink: "/:year-:month-:day/:title"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- tale.gemspec
